import React from 'react';
import type { components } from '@/api/schema';
import { formatCurrency } from '@/utils/formatters';

type Response = components['schemas']['PromiseFromTextResponse'];
interface Props { result: Response; }

export const ExtractionResult: React.FC<Props> = ({ result }) => {
  if (!result.commitment_found || !result.promise) return <div className="mt-5 rounded-lg border border-[var(--color-status-risk)]/30 bg-[var(--color-status-risk)]/10 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--color-primary)]">No commitment recorded</p><h3 className="mt-1 text-lg font-semibold text-[var(--color-primary)]">Correctly declined without guessing</h3><p className="mt-2 text-sm text-[var(--color-text-muted)]">{result.detail}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Refusal reason</dt><dd className="mt-1 font-semibold text-[var(--color-primary)]">{result.refusal_reason ?? 'Not supplied'}</dd></div><div><dt className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Confidence</dt><dd className="mt-1 font-semibold text-[var(--color-primary)]">{result.confidence.toFixed(2)} / {result.confidence_floor.toFixed(2)}</dd></div><div><dt className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Audit extraction</dt><dd className="mt-1 font-mono text-xs text-[var(--color-primary)]">{result.extraction_id}</dd></div></dl></div>;
  return <div className="mt-5 rounded-lg border border-[var(--color-status-recovered)]/30 bg-[var(--color-status-recovered)]/10 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--color-status-recovered)]">Commitment extracted</p><h3 className="mt-1 text-lg font-semibold text-[var(--color-primary)]">Promise recorded with confidence {result.confidence.toFixed(2)}</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Promised amount</p><p className="mt-1 text-xl font-bold text-[var(--color-primary)]">{formatCurrency(result.promise.promised_amount)}</p><p className="text-xs text-[var(--color-text-muted)]">{result.promised_amount_inferred ? 'Inferred from amount at risk' : 'Explicitly stated by customer'}</p></div><div><p className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Promised date</p><p className="mt-1 text-xl font-bold text-[var(--color-primary)]">{result.promise.promised_date}</p></div><div><p className="text-xs uppercase tracking-wide text-[var(--color-text-muted)]">Quote verified</p><p className="mt-1 text-sm font-semibold text-[var(--color-primary)]">“{result.quote ?? 'No quote'}”</p></div></div><p className="mt-4 border-l-2 border-[var(--color-status-recovered)] pl-3 text-sm italic text-[var(--color-primary)]">{result.raw_text}</p></div>;
};
