import React from 'react';
import type { components } from '@/api/schema';
import { formatCurrency } from '@/utils/formatters';

type PromiseToPay = components['schemas']['PromiseToPayDocument'];
interface Props { promises: PromiseToPay[]; }
const stateClass: Record<PromiseToPay['state'], string> = { honored: 'bg-[var(--color-status-recovered)]/10 text-[var(--color-status-recovered)]', broken: 'bg-[var(--color-status-blocked)]/10 text-[var(--color-status-blocked)]', reevaluating: 'bg-[var(--color-status-risk)]/15 text-[var(--color-primary)]', promised: 'bg-gray-100 text-[var(--color-text-muted)]' };

export const PromiseList: React.FC<Props> = ({ promises }) => <section className="rounded-xl border border-gray-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-100 px-6 py-5"><div><h2 className="text-lg font-semibold text-[var(--color-primary)]">Recorded promises</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">Newest first. The promise API does not expose input origin, so origin is intentionally not inferred here.</p></div><span className="rounded-full bg-[var(--color-bg-surface)] px-3 py-1 text-xs font-semibold text-[var(--color-text-muted)]">{promises.length} total</span></div><div className="max-h-[430px] overflow-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="sticky top-0 bg-[var(--color-bg-surface)] text-xs uppercase tracking-wide text-[var(--color-text-muted)]"><tr><th className="px-6 py-3 font-medium">Event</th><th className="px-6 py-3 font-medium">Amount</th><th className="px-6 py-3 font-medium">Promise date</th><th className="px-6 py-3 font-medium">State</th><th className="px-6 py-3 font-medium">Origin</th></tr></thead><tbody className="divide-y divide-gray-50">{promises.map((promise) => <tr key={promise.id}><td className="px-6 py-4 font-mono text-xs text-[var(--color-primary)]">{promise.event_id}</td><td className="px-6 py-4 font-semibold">{formatCurrency(promise.promised_amount)}</td><td className="px-6 py-4 text-[var(--color-text-muted)]">{promise.promised_date}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${stateClass[promise.state]}`}>{promise.state}</span></td><td className="px-6 py-4 text-xs text-[var(--color-text-muted)]">Not exposed by API</td></tr>)}</tbody></table></div></section>;
